trigger:
- master  # Define the branch that triggers the pipeline

pool:
  vmImage: 'windows-latest'  # Use a Windows agent, change to 'ubuntu-latest' for a Linux agent

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.x'  # Replace '3.x' with the desired Python version
  inputs:
    versionSpec: '3.x'
    addToPath: true  # Adds Python to the PATH

- script: |
    python -c "print('Hello, World!')"
  displayName: 'Run Python Script'