trigger:
- master  # Define the branch that triggers the pipeline

pool:
  vmImage: 'windows-latest'  # Use a Windows agent, change to 'ubuntu-latest' for a Linux agent

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    addToPath: true
    architecture: 'x64'

- script: |
    python -c "print('Hello, World!')"
  displayName: 'Run Python Script'