trigger:
- master  # Define the branch that triggers the pipeline

pool:
  vmImage: 'windows-latest'  # Use a Windows agent, change to 'ubuntu-latest' for a Linux agent

steps:
- script: |
    curl -o python_installer.exe https://www.python.org/ftp/python/3.12.0/python-3.12.0-amd64.exe
    python_installer.exe /quiet InstallAllUsers=1 PrependPath=1 Include_test=0
  displayName: 'Install Python 3.12.0 x64'
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12.0'
    addToPath: true
    architecture: 'x64'

- script: |
    python -c "print('Hello, World!')"
  displayName: 'Run Python Script'